/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCylinderExchangeRouteImport } from './routes/_authenticated/cylinder-exchange'
import { Route as AuthenticatedCylinderPurchasesRouteImport } from './routes/_authenticated/cylinder-purchases'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedLocalFillingRouteImport } from './routes/_authenticated/local-filling'
import { Route as AuthenticatedMovementsRouteImport } from './routes/_authenticated/movements'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedProfitRouteImport } from './routes/_authenticated/profit'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedVehiclesRouteImport } from './routes/_authenticated/vehicles'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCylinderExchangeRoute =
  AuthenticatedCylinderExchangeRouteImport.update({
    id: '/cylinder-exchange',
    path: '/cylinder-exchange',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCylinderPurchasesRoute =
  AuthenticatedCylinderPurchasesRouteImport.update({
    id: '/cylinder-purchases',
    path: '/cylinder-purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocalFillingRoute =
  AuthenticatedLocalFillingRouteImport.update({
    id: '/local-filling',
    path: '/local-filling',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMovementsRoute = AuthenticatedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitRoute = AuthenticatedProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesRoute = AuthenticatedVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/cylinder-exchange': typeof AuthenticatedCylinderExchangeRoute
  '/cylinder-purchases': typeof AuthenticatedCylinderPurchasesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/local-filling': typeof AuthenticatedLocalFillingRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/cylinder-exchange': typeof AuthenticatedCylinderExchangeRoute
  '/cylinder-purchases': typeof AuthenticatedCylinderPurchasesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/local-filling': typeof AuthenticatedLocalFillingRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/vehicles': typeof AuthenticatedVehiclesRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/cylinder-exchange': typeof AuthenticatedCylinderExchangeRoute
  '/_authenticated/cylinder-purchases': typeof AuthenticatedCylinderPurchasesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/local-filling': typeof AuthenticatedLocalFillingRoute
  '/_authenticated/movements': typeof AuthenticatedMovementsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/profit': typeof AuthenticatedProfitRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/vehicles': typeof AuthenticatedVehiclesRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit-log'
    | '/backup'
    | '/customers'
    | '/cylinder-exchange'
    | '/cylinder-purchases'
    | '/dashboard'
    | '/drivers'
    | '/employees'
    | '/expenses'
    | '/local-filling'
    | '/movements'
    | '/payments'
    | '/production'
    | '/profit'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/vehicles'
    | '/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit-log'
    | '/backup'
    | '/customers'
    | '/cylinder-exchange'
    | '/cylinder-purchases'
    | '/dashboard'
    | '/drivers'
    | '/employees'
    | '/expenses'
    | '/local-filling'
    | '/movements'
    | '/payments'
    | '/production'
    | '/profit'
    | '/purchases'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/vehicles'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit-log'
    | '/_authenticated/backup'
    | '/_authenticated/customers'
    | '/_authenticated/cylinder-exchange'
    | '/_authenticated/cylinder-purchases'
    | '/_authenticated/dashboard'
    | '/_authenticated/drivers'
    | '/_authenticated/employees'
    | '/_authenticated/expenses'
    | '/_authenticated/local-filling'
    | '/_authenticated/movements'
    | '/_authenticated/payments'
    | '/_authenticated/production'
    | '/_authenticated/profit'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/suppliers'
    | '/_authenticated/vehicles'
    | '/_authenticated/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cylinder-exchange': {
      id: '/_authenticated/cylinder-exchange'
      path: '/cylinder-exchange'
      fullPath: '/cylinder-exchange'
      preLoaderRoute: typeof AuthenticatedCylinderExchangeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cylinder-purchases': {
      id: '/_authenticated/cylinder-purchases'
      path: '/cylinder-purchases'
      fullPath: '/cylinder-purchases'
      preLoaderRoute: typeof AuthenticatedCylinderPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/local-filling': {
      id: '/_authenticated/local-filling'
      path: '/local-filling'
      fullPath: '/local-filling'
      preLoaderRoute: typeof AuthenticatedLocalFillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movements': {
      id: '/_authenticated/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthenticatedMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profit': {
      id: '/_authenticated/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof AuthenticatedProfitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles': {
      id: '/_authenticated/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
  }
}

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersCustomerIdRoute:
      AuthenticatedCustomersCustomerIdRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedCylinderExchangeRoute: typeof AuthenticatedCylinderExchangeRoute
  AuthenticatedCylinderPurchasesRoute: typeof AuthenticatedCylinderPurchasesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedLocalFillingRoute: typeof AuthenticatedLocalFillingRoute
  AuthenticatedMovementsRoute: typeof AuthenticatedMovementsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProfitRoute: typeof AuthenticatedProfitRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedVehiclesRoute: typeof AuthenticatedVehiclesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedCylinderExchangeRoute: AuthenticatedCylinderExchangeRoute,
  AuthenticatedCylinderPurchasesRoute: AuthenticatedCylinderPurchasesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedLocalFillingRoute: AuthenticatedLocalFillingRoute,
  AuthenticatedMovementsRoute: AuthenticatedMovementsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProfitRoute: AuthenticatedProfitRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedVehiclesRoute: AuthenticatedVehiclesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
